name = "roverse"
main = "main.wasm"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "games.${PROXY_DOMAIN}", custom_domain = true },
  { pattern = "friends.${PROXY_DOMAIN}", custom_domain = true },
  { pattern = "users.${PROXY_DOMAIN}", custom_domain = true },
  { pattern = "avatar.${PROXY_DOMAIN}", custom_domain = true },
  { pattern = "groups.${PROXY_DOMAIN}", custom_domain = true },
  { pattern = "presence.${PROXY_DOMAIN}", custom_domain = true },
  { pattern = "thumbnails.${PROXY_DOMAIN}", custom_domain = true }
]

[observability.logs]
enabled = true

[vars]
PROXY_SECRET_KEY = "1472F"
