name = "roverse"
main = "./build/worker.mjs"
compatibility_date = "2024-04-15"

routes = [
  "users.roverse.gonzaza5752.workers.dev/*",
  "games.roverse.gonzaza5752.workers.dev/*",
  "friends.roverse.gonzaza5752.workers.dev/*",
  "avatar.roverse.gonzaza5752.workers.dev/*",
  "groups.roverse.gonzaza5752.workers.dev/*",
  "presence.roverse.gonzaza5752.workers.dev/*",
  "thumbnails.roverse.gonzaza5752.workers.dev/*"
]

[vars]
PROXY_SECRET_KEY = "1472F"
